// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cbiMsg.proto

package com.cbim.cbim.proto;

public final class CbiMsg {
  private CbiMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cbim.cbim.proto.MsgProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
     */
    boolean hasScoreList();
    /**
     * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
     */
    com.cbim.cbim.proto.CbiMsg.ScoreProtoList getScoreList();
    /**
     * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
     */
    com.cbim.cbim.proto.CbiMsg.ScoreProtoListOrBuilder getScoreListOrBuilder();
  }
  /**
   * Protobuf type {@code com.cbim.cbim.proto.MsgProto}
   */
  public  static final class MsgProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cbim.cbim.proto.MsgProto)
      MsgProtoOrBuilder {
    // Use MsgProto.newBuilder() to construct.
    private MsgProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgProto() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = scoreList_.toBuilder();
              }
              scoreList_ = input.readMessage(com.cbim.cbim.proto.CbiMsg.ScoreProtoList.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(scoreList_);
                scoreList_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_MsgProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_MsgProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cbim.cbim.proto.CbiMsg.MsgProto.class, com.cbim.cbim.proto.CbiMsg.MsgProto.Builder.class);
    }

    private int bitField0_;
    public static final int SCORELIST_FIELD_NUMBER = 1;
    private com.cbim.cbim.proto.CbiMsg.ScoreProtoList scoreList_;
    /**
     * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
     */
    public boolean hasScoreList() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
     */
    public com.cbim.cbim.proto.CbiMsg.ScoreProtoList getScoreList() {
      return scoreList_ == null ? com.cbim.cbim.proto.CbiMsg.ScoreProtoList.getDefaultInstance() : scoreList_;
    }
    /**
     * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
     */
    public com.cbim.cbim.proto.CbiMsg.ScoreProtoListOrBuilder getScoreListOrBuilder() {
      return scoreList_ == null ? com.cbim.cbim.proto.CbiMsg.ScoreProtoList.getDefaultInstance() : scoreList_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasScoreList()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getScoreList().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getScoreList());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getScoreList());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cbim.cbim.proto.CbiMsg.MsgProto)) {
        return super.equals(obj);
      }
      com.cbim.cbim.proto.CbiMsg.MsgProto other = (com.cbim.cbim.proto.CbiMsg.MsgProto) obj;

      boolean result = true;
      result = result && (hasScoreList() == other.hasScoreList());
      if (hasScoreList()) {
        result = result && getScoreList()
            .equals(other.getScoreList());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasScoreList()) {
        hash = (37 * hash) + SCORELIST_FIELD_NUMBER;
        hash = (53 * hash) + getScoreList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.MsgProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cbim.cbim.proto.CbiMsg.MsgProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cbim.cbim.proto.MsgProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cbim.cbim.proto.MsgProto)
        com.cbim.cbim.proto.CbiMsg.MsgProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_MsgProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_MsgProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cbim.cbim.proto.CbiMsg.MsgProto.class, com.cbim.cbim.proto.CbiMsg.MsgProto.Builder.class);
      }

      // Construct using com.cbim.cbim.proto.CbiMsg.MsgProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getScoreListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (scoreListBuilder_ == null) {
          scoreList_ = null;
        } else {
          scoreListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_MsgProto_descriptor;
      }

      public com.cbim.cbim.proto.CbiMsg.MsgProto getDefaultInstanceForType() {
        return com.cbim.cbim.proto.CbiMsg.MsgProto.getDefaultInstance();
      }

      public com.cbim.cbim.proto.CbiMsg.MsgProto build() {
        com.cbim.cbim.proto.CbiMsg.MsgProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cbim.cbim.proto.CbiMsg.MsgProto buildPartial() {
        com.cbim.cbim.proto.CbiMsg.MsgProto result = new com.cbim.cbim.proto.CbiMsg.MsgProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (scoreListBuilder_ == null) {
          result.scoreList_ = scoreList_;
        } else {
          result.scoreList_ = scoreListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cbim.cbim.proto.CbiMsg.MsgProto) {
          return mergeFrom((com.cbim.cbim.proto.CbiMsg.MsgProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cbim.cbim.proto.CbiMsg.MsgProto other) {
        if (other == com.cbim.cbim.proto.CbiMsg.MsgProto.getDefaultInstance()) return this;
        if (other.hasScoreList()) {
          mergeScoreList(other.getScoreList());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasScoreList()) {
          return false;
        }
        if (!getScoreList().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cbim.cbim.proto.CbiMsg.MsgProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cbim.cbim.proto.CbiMsg.MsgProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.cbim.cbim.proto.CbiMsg.ScoreProtoList scoreList_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cbim.cbim.proto.CbiMsg.ScoreProtoList, com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder, com.cbim.cbim.proto.CbiMsg.ScoreProtoListOrBuilder> scoreListBuilder_;
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public boolean hasScoreList() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProtoList getScoreList() {
        if (scoreListBuilder_ == null) {
          return scoreList_ == null ? com.cbim.cbim.proto.CbiMsg.ScoreProtoList.getDefaultInstance() : scoreList_;
        } else {
          return scoreListBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public Builder setScoreList(com.cbim.cbim.proto.CbiMsg.ScoreProtoList value) {
        if (scoreListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          scoreList_ = value;
          onChanged();
        } else {
          scoreListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public Builder setScoreList(
          com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder builderForValue) {
        if (scoreListBuilder_ == null) {
          scoreList_ = builderForValue.build();
          onChanged();
        } else {
          scoreListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public Builder mergeScoreList(com.cbim.cbim.proto.CbiMsg.ScoreProtoList value) {
        if (scoreListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              scoreList_ != null &&
              scoreList_ != com.cbim.cbim.proto.CbiMsg.ScoreProtoList.getDefaultInstance()) {
            scoreList_ =
              com.cbim.cbim.proto.CbiMsg.ScoreProtoList.newBuilder(scoreList_).mergeFrom(value).buildPartial();
          } else {
            scoreList_ = value;
          }
          onChanged();
        } else {
          scoreListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public Builder clearScoreList() {
        if (scoreListBuilder_ == null) {
          scoreList_ = null;
          onChanged();
        } else {
          scoreListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder getScoreListBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getScoreListFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProtoListOrBuilder getScoreListOrBuilder() {
        if (scoreListBuilder_ != null) {
          return scoreListBuilder_.getMessageOrBuilder();
        } else {
          return scoreList_ == null ?
              com.cbim.cbim.proto.CbiMsg.ScoreProtoList.getDefaultInstance() : scoreList_;
        }
      }
      /**
       * <code>required .com.cbim.cbim.proto.ScoreProtoList scoreList = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cbim.cbim.proto.CbiMsg.ScoreProtoList, com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder, com.cbim.cbim.proto.CbiMsg.ScoreProtoListOrBuilder> 
          getScoreListFieldBuilder() {
        if (scoreListBuilder_ == null) {
          scoreListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.cbim.cbim.proto.CbiMsg.ScoreProtoList, com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder, com.cbim.cbim.proto.CbiMsg.ScoreProtoListOrBuilder>(
                  getScoreList(),
                  getParentForChildren(),
                  isClean());
          scoreList_ = null;
        }
        return scoreListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cbim.cbim.proto.MsgProto)
    }

    // @@protoc_insertion_point(class_scope:com.cbim.cbim.proto.MsgProto)
    private static final com.cbim.cbim.proto.CbiMsg.MsgProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cbim.cbim.proto.CbiMsg.MsgProto();
    }

    public static com.cbim.cbim.proto.CbiMsg.MsgProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MsgProto>
        PARSER = new com.google.protobuf.AbstractParser<MsgProto>() {
      public MsgProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgProto> getParserForType() {
      return PARSER;
    }

    public com.cbim.cbim.proto.CbiMsg.MsgProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScoreProtoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cbim.cbim.proto.ScoreProtoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    java.util.List<com.cbim.cbim.proto.CbiMsg.ScoreProto> 
        getListList();
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    com.cbim.cbim.proto.CbiMsg.ScoreProto getList(int index);
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    java.util.List<? extends com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.cbim.cbim.proto.ScoreProtoList}
   */
  public  static final class ScoreProtoList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cbim.cbim.proto.ScoreProtoList)
      ScoreProtoListOrBuilder {
    // Use ScoreProtoList.newBuilder() to construct.
    private ScoreProtoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScoreProtoList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScoreProtoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<com.cbim.cbim.proto.CbiMsg.ScoreProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.cbim.cbim.proto.CbiMsg.ScoreProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProtoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cbim.cbim.proto.CbiMsg.ScoreProtoList.class, com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.cbim.cbim.proto.CbiMsg.ScoreProto> list_;
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    public java.util.List<com.cbim.cbim.proto.CbiMsg.ScoreProto> getListList() {
      return list_;
    }
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    public java.util.List<? extends com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    public com.cbim.cbim.proto.CbiMsg.ScoreProto getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
     */
    public com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cbim.cbim.proto.CbiMsg.ScoreProtoList)) {
        return super.equals(obj);
      }
      com.cbim.cbim.proto.CbiMsg.ScoreProtoList other = (com.cbim.cbim.proto.CbiMsg.ScoreProtoList) obj;

      boolean result = true;
      result = result && getListList()
          .equals(other.getListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cbim.cbim.proto.CbiMsg.ScoreProtoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cbim.cbim.proto.ScoreProtoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cbim.cbim.proto.ScoreProtoList)
        com.cbim.cbim.proto.CbiMsg.ScoreProtoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProtoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProtoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cbim.cbim.proto.CbiMsg.ScoreProtoList.class, com.cbim.cbim.proto.CbiMsg.ScoreProtoList.Builder.class);
      }

      // Construct using com.cbim.cbim.proto.CbiMsg.ScoreProtoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProtoList_descriptor;
      }

      public com.cbim.cbim.proto.CbiMsg.ScoreProtoList getDefaultInstanceForType() {
        return com.cbim.cbim.proto.CbiMsg.ScoreProtoList.getDefaultInstance();
      }

      public com.cbim.cbim.proto.CbiMsg.ScoreProtoList build() {
        com.cbim.cbim.proto.CbiMsg.ScoreProtoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cbim.cbim.proto.CbiMsg.ScoreProtoList buildPartial() {
        com.cbim.cbim.proto.CbiMsg.ScoreProtoList result = new com.cbim.cbim.proto.CbiMsg.ScoreProtoList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cbim.cbim.proto.CbiMsg.ScoreProtoList) {
          return mergeFrom((com.cbim.cbim.proto.CbiMsg.ScoreProtoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cbim.cbim.proto.CbiMsg.ScoreProtoList other) {
        if (other == com.cbim.cbim.proto.CbiMsg.ScoreProtoList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cbim.cbim.proto.CbiMsg.ScoreProtoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cbim.cbim.proto.CbiMsg.ScoreProtoList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.cbim.cbim.proto.CbiMsg.ScoreProto> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<com.cbim.cbim.proto.CbiMsg.ScoreProto>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.cbim.cbim.proto.CbiMsg.ScoreProto, com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder, com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder> listBuilder_;

      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public java.util.List<com.cbim.cbim.proto.CbiMsg.ScoreProto> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProto getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder setList(
          int index, com.cbim.cbim.proto.CbiMsg.ScoreProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder setList(
          int index, com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder addList(com.cbim.cbim.proto.CbiMsg.ScoreProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder addList(
          int index, com.cbim.cbim.proto.CbiMsg.ScoreProto value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder addList(
          com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder addList(
          int index, com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.cbim.cbim.proto.CbiMsg.ScoreProto> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public java.util.List<? extends com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.cbim.cbim.proto.CbiMsg.ScoreProto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.cbim.cbim.proto.CbiMsg.ScoreProto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.cbim.cbim.proto.ScoreProto list = 1;</code>
       */
      public java.util.List<com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.cbim.cbim.proto.CbiMsg.ScoreProto, com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder, com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.cbim.cbim.proto.CbiMsg.ScoreProto, com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder, com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cbim.cbim.proto.ScoreProtoList)
    }

    // @@protoc_insertion_point(class_scope:com.cbim.cbim.proto.ScoreProtoList)
    private static final com.cbim.cbim.proto.CbiMsg.ScoreProtoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cbim.cbim.proto.CbiMsg.ScoreProtoList();
    }

    public static com.cbim.cbim.proto.CbiMsg.ScoreProtoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ScoreProtoList>
        PARSER = new com.google.protobuf.AbstractParser<ScoreProtoList>() {
      public ScoreProtoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ScoreProtoList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScoreProtoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreProtoList> getParserForType() {
      return PARSER;
    }

    public com.cbim.cbim.proto.CbiMsg.ScoreProtoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScoreProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cbim.cbim.proto.ScoreProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 chinese = 2;</code>
     */
    boolean hasChinese();
    /**
     * <code>required int32 chinese = 2;</code>
     */
    int getChinese();

    /**
     * <code>required int32 math = 3;</code>
     */
    boolean hasMath();
    /**
     * <code>required int32 math = 3;</code>
     */
    int getMath();

    /**
     * <code>required int32 english = 4;</code>
     */
    boolean hasEnglish();
    /**
     * <code>required int32 english = 4;</code>
     */
    int getEnglish();
  }
  /**
   * Protobuf type {@code com.cbim.cbim.proto.ScoreProto}
   */
  public  static final class ScoreProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cbim.cbim.proto.ScoreProto)
      ScoreProtoOrBuilder {
    // Use ScoreProto.newBuilder() to construct.
    private ScoreProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScoreProto() {
      name_ = "";
      chinese_ = 0;
      math_ = 0;
      english_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScoreProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              chinese_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              math_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              english_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cbim.cbim.proto.CbiMsg.ScoreProto.class, com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHINESE_FIELD_NUMBER = 2;
    private int chinese_;
    /**
     * <code>required int32 chinese = 2;</code>
     */
    public boolean hasChinese() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 chinese = 2;</code>
     */
    public int getChinese() {
      return chinese_;
    }

    public static final int MATH_FIELD_NUMBER = 3;
    private int math_;
    /**
     * <code>required int32 math = 3;</code>
     */
    public boolean hasMath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 math = 3;</code>
     */
    public int getMath() {
      return math_;
    }

    public static final int ENGLISH_FIELD_NUMBER = 4;
    private int english_;
    /**
     * <code>required int32 english = 4;</code>
     */
    public boolean hasEnglish() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 english = 4;</code>
     */
    public int getEnglish() {
      return english_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChinese()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnglish()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, chinese_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, math_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, english_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chinese_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, math_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, english_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cbim.cbim.proto.CbiMsg.ScoreProto)) {
        return super.equals(obj);
      }
      com.cbim.cbim.proto.CbiMsg.ScoreProto other = (com.cbim.cbim.proto.CbiMsg.ScoreProto) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasChinese() == other.hasChinese());
      if (hasChinese()) {
        result = result && (getChinese()
            == other.getChinese());
      }
      result = result && (hasMath() == other.hasMath());
      if (hasMath()) {
        result = result && (getMath()
            == other.getMath());
      }
      result = result && (hasEnglish() == other.hasEnglish());
      if (hasEnglish()) {
        result = result && (getEnglish()
            == other.getEnglish());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasChinese()) {
        hash = (37 * hash) + CHINESE_FIELD_NUMBER;
        hash = (53 * hash) + getChinese();
      }
      if (hasMath()) {
        hash = (37 * hash) + MATH_FIELD_NUMBER;
        hash = (53 * hash) + getMath();
      }
      if (hasEnglish()) {
        hash = (37 * hash) + ENGLISH_FIELD_NUMBER;
        hash = (53 * hash) + getEnglish();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cbim.cbim.proto.CbiMsg.ScoreProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cbim.cbim.proto.CbiMsg.ScoreProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cbim.cbim.proto.ScoreProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cbim.cbim.proto.ScoreProto)
        com.cbim.cbim.proto.CbiMsg.ScoreProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cbim.cbim.proto.CbiMsg.ScoreProto.class, com.cbim.cbim.proto.CbiMsg.ScoreProto.Builder.class);
      }

      // Construct using com.cbim.cbim.proto.CbiMsg.ScoreProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        chinese_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        math_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        english_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cbim.cbim.proto.CbiMsg.internal_static_com_cbim_cbim_proto_ScoreProto_descriptor;
      }

      public com.cbim.cbim.proto.CbiMsg.ScoreProto getDefaultInstanceForType() {
        return com.cbim.cbim.proto.CbiMsg.ScoreProto.getDefaultInstance();
      }

      public com.cbim.cbim.proto.CbiMsg.ScoreProto build() {
        com.cbim.cbim.proto.CbiMsg.ScoreProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cbim.cbim.proto.CbiMsg.ScoreProto buildPartial() {
        com.cbim.cbim.proto.CbiMsg.ScoreProto result = new com.cbim.cbim.proto.CbiMsg.ScoreProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chinese_ = chinese_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.math_ = math_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.english_ = english_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cbim.cbim.proto.CbiMsg.ScoreProto) {
          return mergeFrom((com.cbim.cbim.proto.CbiMsg.ScoreProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cbim.cbim.proto.CbiMsg.ScoreProto other) {
        if (other == com.cbim.cbim.proto.CbiMsg.ScoreProto.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasChinese()) {
          setChinese(other.getChinese());
        }
        if (other.hasMath()) {
          setMath(other.getMath());
        }
        if (other.hasEnglish()) {
          setEnglish(other.getEnglish());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasChinese()) {
          return false;
        }
        if (!hasMath()) {
          return false;
        }
        if (!hasEnglish()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cbim.cbim.proto.CbiMsg.ScoreProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cbim.cbim.proto.CbiMsg.ScoreProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int chinese_ ;
      /**
       * <code>required int32 chinese = 2;</code>
       */
      public boolean hasChinese() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 chinese = 2;</code>
       */
      public int getChinese() {
        return chinese_;
      }
      /**
       * <code>required int32 chinese = 2;</code>
       */
      public Builder setChinese(int value) {
        bitField0_ |= 0x00000002;
        chinese_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 chinese = 2;</code>
       */
      public Builder clearChinese() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chinese_ = 0;
        onChanged();
        return this;
      }

      private int math_ ;
      /**
       * <code>required int32 math = 3;</code>
       */
      public boolean hasMath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 math = 3;</code>
       */
      public int getMath() {
        return math_;
      }
      /**
       * <code>required int32 math = 3;</code>
       */
      public Builder setMath(int value) {
        bitField0_ |= 0x00000004;
        math_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 math = 3;</code>
       */
      public Builder clearMath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        math_ = 0;
        onChanged();
        return this;
      }

      private int english_ ;
      /**
       * <code>required int32 english = 4;</code>
       */
      public boolean hasEnglish() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 english = 4;</code>
       */
      public int getEnglish() {
        return english_;
      }
      /**
       * <code>required int32 english = 4;</code>
       */
      public Builder setEnglish(int value) {
        bitField0_ |= 0x00000008;
        english_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 english = 4;</code>
       */
      public Builder clearEnglish() {
        bitField0_ = (bitField0_ & ~0x00000008);
        english_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cbim.cbim.proto.ScoreProto)
    }

    // @@protoc_insertion_point(class_scope:com.cbim.cbim.proto.ScoreProto)
    private static final com.cbim.cbim.proto.CbiMsg.ScoreProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cbim.cbim.proto.CbiMsg.ScoreProto();
    }

    public static com.cbim.cbim.proto.CbiMsg.ScoreProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ScoreProto>
        PARSER = new com.google.protobuf.AbstractParser<ScoreProto>() {
      public ScoreProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ScoreProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScoreProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreProto> getParserForType() {
      return PARSER;
    }

    public com.cbim.cbim.proto.CbiMsg.ScoreProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cbim_cbim_proto_MsgProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cbim_cbim_proto_MsgProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cbim_cbim_proto_ScoreProtoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cbim_cbim_proto_ScoreProtoList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cbim_cbim_proto_ScoreProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cbim_cbim_proto_ScoreProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014cbiMsg.proto\022\023com.cbim.cbim.proto\"B\n\010M" +
      "sgProto\0226\n\tscoreList\030\001 \002(\0132#.com.cbim.cb" +
      "im.proto.ScoreProtoList\"?\n\016ScoreProtoLis" +
      "t\022-\n\004list\030\001 \003(\0132\037.com.cbim.cbim.proto.Sc" +
      "oreProto\"J\n\nScoreProto\022\014\n\004name\030\001 \002(\t\022\017\n\007" +
      "chinese\030\002 \002(\005\022\014\n\004math\030\003 \002(\005\022\017\n\007english\030\004" +
      " \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cbim_cbim_proto_MsgProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cbim_cbim_proto_MsgProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cbim_cbim_proto_MsgProto_descriptor,
        new java.lang.String[] { "ScoreList", });
    internal_static_com_cbim_cbim_proto_ScoreProtoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cbim_cbim_proto_ScoreProtoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cbim_cbim_proto_ScoreProtoList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_com_cbim_cbim_proto_ScoreProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_cbim_cbim_proto_ScoreProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cbim_cbim_proto_ScoreProto_descriptor,
        new java.lang.String[] { "Name", "Chinese", "Math", "English", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
